FROM openjdk:11

EXPOSE 8070

ADD ./target/contentanalysing-service-0.0.1-SNAPSHOT.jar contentanalysing-service-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/contentanalysing-service-0.0.1-SNAPSHOT.jar"]
