FROM openjdk:11

EXPOSE 8097

ADD ./target/questionanswer-service-0.0.1-SNAPSHOT.jar questionanswer-service-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/questionanswer-service-0.0.1-SNAPSHOT.jar"]
